# Augmented Python Reference

This notebook **expands on** the [original shorter reference material](https://github.com/gamesbyjames/spanish-flash/blob/main/zero_to_hero_python_reference.ipynb). It provides **additional** Python concepts at a beginner-to-intermediate level, including:

1. Advanced List Operations & Comprehensions
2. NumPy Array Operations
3. Functional Programming (map, filter, reduce, lambdas)
4. Object-Oriented Programming (OOP)
5. Decorators
6. Context Managers
7. Python Type Hints
8. Efficient Iteration (Generators, itertools, Batching)
9. Error Handling (try/except, raising exceptions)
10. Advanced String Formatting (f-strings, etc.)

All code is pure Python + NumPy (no deep learning frameworks). **Run each cell** to see outputs and try the interactive quizzes.

## Setup (Imports)

Make sure you have the following installed:
- `ipywidgets` (for interactive quizzes)
- `numpy`

Then import them here:

In [20]:
import ipywidgets as widgets
from IPython.display import display, clear_output
import numpy as np

# 1. Advanced List Operations & Comprehensions

You may know basic list comprehensions (e.g., `[x+1 for x in some_list]`). Below are some **advanced** or **less common** uses:
- Nested list comprehensions
- Using `zip` to combine lists in parallel
- "Unzipping" data with `zip(*list_of_pairs)`

These patterns are often used in data preprocessing and batch creation in machine learning code (although we’re not using a deep learning library here).

In [21]:
# Example: Nested list comprehension to flatten a 2D list
# 'matrix' is a list of lists. We want to collect all elements into a single list.
matrix = [[1, 2, 3], [4, 5, 6]]
# The comprehension below reads:
#   for each sublist x in matrix,
#       for each element y in x,
#           produce y
flattened = [y for x in matrix for y in x]
print("Original matrix:", matrix)
print("Flattened list:", flattened)

Original matrix: [[1, 2, 3], [4, 5, 6]]
Flattened list: [1, 2, 3, 4, 5, 6]


### Parallel Iteration with `zip`

You can **zip** two (or more) lists to iterate over them in parallel. This returns pairs (tuples) of corresponding elements.

In [22]:
list1 = [1, 2, 3]
list2 = [10, 20, 30]

# Zipping them creates pairs like (1,10), (2,20), (3,30)
paired = list(zip(list1, list2))
print("Zipped pairs:", paired)

# We can do element-wise addition by unpacking each pair in a comprehension:
sum_list = [a + b for (a, b) in zip(list1, list2)]
print("Element-wise sums:", sum_list)

# 'Unzipping' with zip(*...) splits paired data back:
nums, tens = zip(*paired)
print("Unzipped nums:", nums)
print("Unzipped tens:", tens)

Zipped pairs: [(1, 10), (2, 20), (3, 30)]
Element-wise sums: [11, 22, 33]
Unzipped nums: (1, 2, 3)
Unzipped tens: (10, 20, 30)


### Quiz

What will be the result of this code?
```python
matrix = [[1, 2], [3, 4], [5, 6]]
result = [y*2 for x in matrix for y in x if y % 2 == 1]
print(result)
```
*(Hint: it doubles the odd numbers. The odd elements in each sublist are 1,3,5.)*

In [24]:
quiz1_options = [
    "[2, 6, 10]",
    "[2, 4, 6, 8, 10, 12]",
    "[2, 6, 10, 12]"
]

quiz1_radio = widgets.RadioButtons(
    options=quiz1_options,
    description='Possible Output:'
)
quiz1_output = widgets.Output()

def on_quiz1_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        with quiz1_output:
            clear_output()
            if change['new'] == "[2, 6, 10]":
                print("✅ Correct! It's doubling 1,3,5 -> 2,6,10.")
            else:
                print("❌ Try again...")

quiz1_radio.observe(on_quiz1_change, names='value')
display(quiz1_radio, quiz1_output)

RadioButtons(description='Possible Output:', options=('[2, 6, 10]', '[2, 4, 6, 8, 10, 12]', '[2, 6, 10, 12]'),…

Output()

# 2. NumPy Array Operations

NumPy is central to numerical computing in Python. Key features include:

- **Array creation** (`np.array`, `np.zeros`, `np.ones`, etc.)
- **Broadcasting** (automatic expansion of dimensions for arithmetic)
- **Slicing/Indexing** (like Python lists, but extended to multiple dimensions)
- **Reshaping** (change shape without changing data)
- **Element-wise math** (e.g., `np.sin`, `a + b`, `a * b`, etc.)

In [25]:
import numpy as np

# Create a 2x3 array
a = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Array a:\n", a)

# Create a 1D array of length 3
b = np.array([10, 20, 30])
print("\nArray b:", b)

# Broadcasting: b is shape (3,), a is (2,3). b is added to each row of a.
print("\nBroadcasted a + b:\n", a + b)

Array a:
 [[1 2 3]
 [4 5 6]]

Array b: [10 20 30]

Broadcasted a + b:
 [[11 22 33]
 [14 25 36]]


In [26]:
# Slicing: extracting subarrays
subarray = a[:, :2]  # all rows, first 2 columns
print("First two columns of a:\n", subarray)

# Reshaping
reshaped = a.reshape(3, 2)
print("\nReshaped a to 3x2:\n", reshaped)

flattened = a.reshape(-1)
print("\nFlattened a:\n", flattened)

First two columns of a:
 [[1 2]
 [4 5]]

Reshaped a to 3x2:
 [[1 2]
 [3 4]
 [5 6]]

Flattened a:
 [1 2 3 4 5 6]


In [27]:
# Element-wise math
print("Element-wise multiplication (a * 2):\n", a * 2)
print("Element-wise squaring (a ** 2):\n", a ** 2)
print("Element-wise sine (np.sin(a)):\n", np.sin(a))

# Another broadcasting example
factors = np.array([[2], [3]])  # shape (2,1)
scaled_rows = a * factors
print("\nScaled rows (broadcasted multiplication):\n", scaled_rows)

Element-wise multiplication (a * 2):
 [[ 2  4  6]
 [ 8 10 12]]
Element-wise squaring (a ** 2):
 [[ 1  4  9]
 [16 25 36]]
Element-wise sine (np.sin(a)):
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]

Scaled rows (broadcasted multiplication):
 [[ 2  4  6]
 [12 15 18]]


### Quiz

Suppose `X` is shape `(5,4)` and `v` is shape `(4,)`. If we do `Y = X + v`, what is `Y.shape` due to broadcasting?

In [29]:
quiz2_options = ["(5, 4)", "(4, 5)", "(5, 4, 4)", "Broadcasting not possible"]
quiz2_radio = widgets.RadioButtons(options=quiz2_options, description='Y.shape:')
quiz2_output = widgets.Output()

def on_quiz2_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        with quiz2_output:
            clear_output()
            if change['new'] == "(5, 4)":
                print("✅ Correct! The result is (5,4).")
            else:
                print("❌ Nope, try again.")

quiz2_radio.observe(on_quiz2_change, names='value')
display(quiz2_radio, quiz2_output)

RadioButtons(description='Y.shape:', options=('(5, 4)', '(4, 5)', '(5, 4, 4)', 'Broadcasting not possible'), v…

Output()

# 3. Functional Programming (map, filter, reduce, lambdas)

Besides **list comprehensions**, Python offers `map`, `filter`, and `reduce` for a *functional* style:

- **`map(func, iterable)`**: applies `func` to each element, returning an iterator of results.
- **`filter(func, iterable)`**: keeps elements where `func(elem)` is True.
- **`reduce(func, iterable)`**: repeatedly applies `func` to combine elements into a single value. (In `functools` module.)
- **`lambda`**: an inline (anonymous) function, used for quick transformations.

Many times, list comprehensions are more readable, but these remain common in various codebases.

In [30]:
# We'll show map, filter, and reduce side by side.
# map applies a function to every element,
# filter keeps only elements where the condition is True,
# reduce aggregates to a single value.

nums = [1, 2, 3, 4, 5]

# map() example: square each number
squares = list(map(lambda x: x**2, nums))
print("Squares:", squares)

# filter() example: keep only even numbers
evens = list(filter(lambda x: x % 2 == 0, nums))
print("Evens:", evens)

# reduce() example: multiply all numbers
from functools import reduce
product = reduce(lambda a, b: a * b, nums)
print("Product of all:", product)

# Notice each does a different type of transformation or selection.
# map -> transforms each element,
# filter -> selects certain elements,
# reduce -> combines them all into one value.

Squares: [1, 4, 9, 16, 25]
Evens: [2, 4]
Product of all: 120


### Quiz

Which snippet **also** produces `[2, 3, 4]` (the same result as `list(map(lambda x: x+1, [1, 2, 3]))`)?

In [32]:
quiz3_options = [
    "[x + 1 for x in [1, 2, 3]]",
    "list(filter(lambda x: x+1, [1, 2, 3]))",
    "for x in [1, 2, 3]: x+1"
]

quiz3_radio = widgets.RadioButtons(
    options=quiz3_options,
    description='Pick one:'
)
quiz3_output = widgets.Output()

def on_quiz3_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        with quiz3_output:
            clear_output()
            if change['new'] == "[x + 1 for x in [1, 2, 3]]":
                print("✅ Correct! That list comprehension yields [2,3,4].")
            else:
                print("❌ No, that's not the same result.")

quiz3_radio.observe(on_quiz3_change, names='value')
display(quiz3_radio, quiz3_output)

RadioButtons(description='Pick one:', options=('[x + 1 for x in [1, 2, 3]]', 'list(filter(lambda x: x+1, [1, 2…

Output()

# 4. Object-Oriented Programming (OOP)

Classes let you bundle data (attributes) and functionality (methods) together. Key OOP ideas:
- **Inheritance**: a subclass extends a base class.
- **Encapsulation**: logically grouping code/data. (Python doesn't enforce strict privacy, but underscores `_var` are used by convention.)
- **Polymorphism**: calling the same method on different classes yields class-specific behavior.

In [33]:
class Animal:
    def __init__(self, name):
        self.name = name
        self._energy = 100

    def speak(self):
        print(f"{self.name} makes a noise.")

    def info(self):
        print(f"{self.name} has energy {self._energy}.")

# Subclasses can override speak()
class Dog(Animal):
    def speak(self):
        print(f"{self.name} says: Woof!")

class Cat(Animal):
    def speak(self):
        print(f"{self.name} says: Meow!")

animals = [Dog("Buddy"), Cat("Whiskers"), Animal("Generic")]  # Polymorphism
for a in animals:
    a.speak()

# We can also call the inherited info() method on Dog or Cat.
animals[0].info()

Buddy says: Woof!
Whiskers says: Meow!
Generic makes a noise.
Buddy has energy 100.


### Quiz

When two subclasses (like `Dog` and `Cat`) each **override** `speak()`, and you call `animal.speak()`, it runs the class-specific method. This is called _____.

In [35]:
quiz4_options = ["Inheritance", "Encapsulation", "Polymorphism", "Abstraction"]
quiz4_radio = widgets.RadioButtons(options=quiz4_options, description='Concept:')
quiz4_output = widgets.Output()

def on_quiz4_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        with quiz4_output:
            clear_output()
            if change['new'] == "Polymorphism":
                print("✅ Correct, that's polymorphism.")
            else:
                print("❌ Try again.")

quiz4_radio.observe(on_quiz4_change, names='value')
display(quiz4_radio, quiz4_output)

RadioButtons(description='Concept:', options=('Inheritance', 'Encapsulation', 'Polymorphism', 'Abstraction'), …

Output()

# 5. Decorators

A **decorator** is a function that takes another function and returns a wrapped version. Decorators are denoted by `@decorator_name` above a function definition and can add cross-cutting behavior like logging, timing, or caching.


In [36]:
import time

def timer(func):
    """A decorator that reports how long 'func' takes to run."""
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        print(f"Function '{func.__name__}' took {end - start:.4f} seconds")
        return result
    return wrapper

@timer
def compute_sum(n):
    total = 0
    for i in range(n):
        total += i
    return total

res = compute_sum(1000000)
print("Result =", res)

Function 'compute_sum' took 0.0530 seconds
Result = 499999500000


### Quiz

In Python, which symbol is used to apply a decorator like `@timer` above a function?

In [37]:
quiz5_options = ["@", "#", "def", "*"]
quiz5_radio = widgets.RadioButtons(options=quiz5_options, description='Symbol:')
quiz5_output = widgets.Output()

def on_quiz5_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        with quiz5_output:
            clear_output()
            if change['new'] == "@":
                print("✅ Correct! Use @decorator above a function.")
            else:
                print("❌ Not correct.")

quiz5_radio.observe(on_quiz5_change, names='value')
display(quiz5_radio, quiz5_output)

RadioButtons(description='Symbol:', options=('@', '#', 'def', '*'), value='@')

Output()

# 6. Context Managers

A **context manager** in Python is an object that sets something up when entering a `with` block and tears it down when exiting, even if an exception occurs. Classic examples:
- `with open('somefile.txt') as f:` ensures the file is closed.
- Custom context managers can handle locks, transactions, etc.

In [38]:
# File handling with 'with': ensures the file is closed automatically.
data = "Some text data\nAnother line"
with open("example.txt", "w") as f:
    f.write(data)

with open("example.txt", "r") as f:
    content = f.read()
    print("File content:\n", content)

File content:
 Some text data
Another line


### Quiz

Why use `with open('data.txt', 'r') as f:` instead of just `f = open('data.txt', 'r')`?

In [39]:
quiz6_options = [
    "It automatically closes the file, even if errors occur.",
    "It’s the only way to read files in Python.",
    "It reads the file much faster.",
    "No specific reason."
]
quiz6_radio = widgets.RadioButtons(options=quiz6_options, description='Reason:')
quiz6_output = widgets.Output()

def on_quiz6_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        with quiz6_output:
            clear_output()
            if change['new'].startswith("It automatically closes"):
                print("✅ Correct! The with-block ensures closure even on error.")
            else:
                print("❌ Not the main reason.")

quiz6_radio.observe(on_quiz6_change, names='value')
display(quiz6_radio, quiz6_output)

RadioButtons(description='Reason:', options=('It automatically closes the file, even if errors occur.', 'It’s …

Output()

# 7. Python Type Hints

Type hints are **optional** annotations that help static checkers (like mypy) and your IDE to catch mismatches, but Python itself doesn’t enforce them at runtime.


In [41]:
from typing import List

def concatenate(words: List[str], sep: str = " ") -> str:
    """Join a list of strings with a separator, returning a single string."""
    return sep.join(words)

# Correct usage
print(concatenate(["deep", "learning"], sep="-"))

# This is logically incorrect, but Python won't stop us at runtime:
# The function expects sep to be a string, but we pass an int.
bad = concatenate(["number", "one"], sep=5)
print("Result with wrong type:", bad)

deep-learning


AttributeError: 'int' object has no attribute 'join'

### Quiz

True or False: *Python will raise a runtime error if you pass a value of the wrong type to a function that has type hints.*

In [43]:
quiz7_options = ["True", "False"]
quiz7_radio = widgets.RadioButtons(options=quiz7_options, description='Answer:')
quiz7_output = widgets.Output()

def on_quiz7_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        with quiz7_output:
            clear_output()
            if change['new'] == "False":
                print("✅ Correct. Type hints are not enforced at runtime.")
            else:
                print("❌ Nope. Hints are only for static checkers.")

quiz7_radio.observe(on_quiz7_change, names='value')
display(quiz7_radio, quiz7_output)

RadioButtons(description='Answer:', options=('True', 'False'), value='True')

Output()

# 8. Efficient Iteration (Generators, itertools, Batching)

For large datasets or infinite streams, **generators** let you yield items one at a time, rather than building an entire list. The `itertools` module provides utility iterators for tasks like grouping, chaining, slicing, etc.

In [44]:
# A generator function uses 'yield' instead of 'return'.
# Each time 'yield' is encountered, one item is produced.
# The function picks up from there next time.

def count_up_to(n):
    i = 1
    while i <= n:
        yield i
        i += 1

gen = count_up_to(5)
print("Generator created:", gen)  # It's an iterator object
print("First value:", next(gen))  # Manually get the first item
print("Remaining values:")
for num in gen:
    print(num)

Generator created: <generator object count_up_to at 0x000001D05EEB02E0>
First value: 1
Remaining values:
2
3
4
5


### Batching example
You might see code that yields data **batches** of a given size. This is typical in ML for mini-batch training.

In [45]:
def batchify(data, batch_size):
    """Yield successive 'batch_size' chunks from 'data'."""
    for i in range(0, len(data), batch_size):
        yield data[i:i+batch_size]

dataset = list(range(1, 11))
for batch in batchify(dataset, 4):
    print(batch)

[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10]


### Quiz

What **keyword** inside a function makes it a generator?

In [47]:
quiz8_options = ["yield", "return", "async", "gen"]
quiz8_radio = widgets.RadioButtons(options=quiz8_options, description='Keyword:')
quiz8_output = widgets.Output()

def on_quiz8_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        with quiz8_output:
            clear_output()
            if change['new'] == "yield":
                print("✅ Correct! 'yield' creates a generator.")
            else:
                print("❌ Try again.")

quiz8_radio.observe(on_quiz8_change, names='value')
display(quiz8_radio, quiz8_output)

RadioButtons(description='Keyword:', options=('yield', 'return', 'async', 'gen'), value='yield')

Output()

# 9. Error Handling (try/except, raising exceptions)

We use `try/except` to handle runtime errors gracefully, and `raise` to signal an error ourselves.

- `try: ... except SomeError:` catches specific exceptions.
- `finally:` runs code whether or not there was an exception.
- `raise ValueError('message')` triggers an exception if we detect invalid input.

In [48]:
def safe_divide(a, b):
    try:
        result = a / b
    except ZeroDivisionError:
        print("Error: cannot divide by zero!")
        result = None
    else:
        print("Division succeeded.")
    finally:
        print("Execution of safe_divide complete.")
    return result

print(safe_divide(10, 2))
print("---")
print(safe_divide(5, 0))

Division succeeded.
Execution of safe_divide complete.
5.0
---
Error: cannot divide by zero!
Execution of safe_divide complete.
None


Raising an exception manually if an invalid condition is found:

In [49]:
def set_learning_rate(lr):
    if lr <= 0:
        raise ValueError(f"Learning rate must be positive, got {lr}")
    print(f"Learning rate set to {lr}")

set_learning_rate(0.01)
try:
    set_learning_rate(0)
except ValueError as e:
    print("Caught exception:", e)

Learning rate set to 0.01
Caught exception: Learning rate must be positive, got 0


### Quiz

Which snippet catches a **missing file** error?

In [51]:
quiz9_options = [
    "try:\n    f = open('data.txt')\nexcept FileNotFoundError:\n    print('File missing')",
    "try:\n    f = open('data.txt')\nexcept KeyError:\n    print('File missing')",
    "try:\n    f = open('data.txt')\nexcept ZeroDivisionError:\n    print('File missing')"
]

quiz9_radio = widgets.RadioButtons(
    options=quiz9_options,
    description='Code:'
)
quiz9_output = widgets.Output()

def on_quiz9_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        with quiz9_output:
            clear_output()
            correct = "try:\n    f = open('data.txt')\nexcept FileNotFoundError:\n    print('File missing')"
            if change['new'] == correct:
                print("✅ Correct! 'FileNotFoundError' is raised if open() can't find the file.")
            else:
                print("❌ Not correct.")

quiz9_radio.observe(on_quiz9_change, names='value')
display(quiz9_radio, quiz9_output)

RadioButtons(description='Code:', options=("try:\n    f = open('data.txt')\nexcept FileNotFoundError:\n    pri…

Output()

# 10. Advanced String Formatting (f-Strings, etc.)

Modern Python uses **f-strings**: `f"Text {variable} more text"` for convenience.

- You can specify format specifiers, e.g. `{value:.2f}` for 2 decimal places.
- Use alignment or zero-padding: `{num:03d}` zero-pads to width 3.
- Great for printing logs with a consistent format.

In [52]:
epoch = 5
loss = 0.123456
print(f"Epoch {epoch} - Loss: {loss}")

value = 7.56789
print(f"value = {value}")
print(f"value to 2 decimal places = {value:.2f}")
print(f"value in scientific notation = {value:.1e}")

num = 42
print(f"number padded (width 5) = {num:05d}")

# Another example in a loop, zero-padding epoch:
for e in range(1, 4):
    train_loss = 0.1 * e
    print(f"[Epoch {e:02d}] Loss = {train_loss:.3f}")

Epoch 5 - Loss: 0.123456
value = 7.56789
value to 2 decimal places = 7.57
value in scientific notation = 7.6e+00
number padded (width 5) = 00042
[Epoch 01] Loss = 0.100
[Epoch 02] Loss = 0.200
[Epoch 03] Loss = 0.300


### Quiz

What does the following code print?
```python
value = 5
print(f"Value = {value:03d}")
```
*(Hint: `:03d` means an integer, width 3, zero-padded.)*

In [54]:
quiz10_options = [
    "Value = 005",
    "Value = 5  ",
    "Value = 0005",
    "Value = 05"
]

quiz10_radio = widgets.RadioButtons(options=quiz10_options, description='Output:')
quiz10_output = widgets.Output()

def on_quiz10_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        with quiz10_output:
            clear_output()
            if change['new'] == "Value = 005":
                print("✅ Correct! 5 -> '005' when padded to width 3.")
            else:
                print("❌ Not correct.")

quiz10_radio.observe(on_quiz10_change, names='value')
display(quiz10_radio, quiz10_output)

RadioButtons(description='Output:', options=('Value = 005', 'Value = 5  ', 'Value = 0005', 'Value = 05'), valu…

Output()

---
## Conclusion

We've covered additional Python features:
- Advanced List Operations
- NumPy Array Manipulation
- Functional Programming
- Object-Oriented Programming
- Decorators
- Context Managers
- Type Hints
- Efficient Iteration (Generators, itertools)
- Error Handling
- Advanced String Formatting

These concepts frequently appear in real-world Python code, including deep learning scripts and data processing pipelines. Refer back here (and to the [original shorter reference](https://github.com/gamesbyjames/spanish-flash/blob/main/zero_to_hero_python_reference.ipynb)) anytime you encounter these constructs. 

Happy Coding!